language: node_js
node_js:
  - 14
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - ghostscript
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_key
  local_dir: dist
  committer_from_gh: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != gh-pages
